version: "3.9"

services:
  app:
    build: .
    container_name: playlister
    ports:
      - "5000:5000"
    environment:
      FLASK_SECURE_COOKIE: "true"
    depends_on:
      - redis
    volumes:
      - .env:/app/.env  # ✅ mount .env into container

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"