name: Deploy to Raspberry Pi

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file from secrets
        run: |
          cat <<EOF > ~/Playlister/.env
          SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REDIRECT_URI=${{ secrets.SPOTIFY_REDIRECT_URI }}
          FLASK_SECURE_COOKIE=true
          REDIS_HOST=redis
          EOF

      - name: Build + Restart Docker
        run: |
          cd ~/Playlister
          git fetch origin
          git reset --hard origin/main
          docker compose down
          docker compose up -d --build